wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934688_Heavy_IGHM.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934687_Heavy_IGHM.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934689_Heavy_IGHM.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934690_Heavy_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934660_Light_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934661_Light_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934662_Light_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934663_Light_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934664_Light_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934665_Light_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934666_Light_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934667_Light_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934672_Heavy_IGHM.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934673_Heavy_IGHM.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934674_Heavy_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934674_Heavy_IGHM.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934675_Heavy_IGHM.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934676_Heavy_IGHM.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934677_Heavy_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934677_Heavy_IGHM.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934678_Heavy_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934678_Heavy_IGHM.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934679_Heavy_IGHM.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934680_Light_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934682_Light_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934683_Light_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934684_Heavy_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934684_Light_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934685_Light_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934686_Heavy_IGHM.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934687_Heavy_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934690_Heavy_IGHM.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934691_Heavy_IGHM.csv.gz