wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934652_Light_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934653_Light_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934654_Light_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934655_Light_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934656_Light_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934657_Light_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934658_Light_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934659_Light_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934668_Heavy_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934668_Heavy_IGHM.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934669_Heavy_IGHM.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934670_Heavy_Bulk.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934670_Heavy_IGHM.csv.gz
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/unpaired/Wesemann_2013/csv/SRR934671_Heavy_IGHM.csv.gz